### ISSUE TITLE
Drop rustc-serialize dependency

### ISSUE THREAD

**Issue by dtolnay** [hugues31/coinnect#10]
It has been deprecated: [announcement](https://users.rust-lang.org/t/deprecation-of-rustc-serialize/10485?u=dtolnay).

**Comment by hugues31** [comment]
Thanks for reporting. I will look into it at the end of the week

**Comment by hugues31** [comment]
Replace rusts-serialize  in favor of data-encoding with 565abf138b928d5548f480420ceedfa82fd821c5
