### ISSUE TITLE
Move error handling to error_chain

### ISSUE THREAD

**Issue by Peltoche** [hugues31/coinnect#12]
Hi, 

I see that for now the error handling is hand made. It's cool but it have a lot of missing features:
- It not generic
- It lost many logs
- It heavy to add a new error

Without a proper error handling system you can't correctly return  all the errors which lead to all the unnecessary `unwrap` call. If you don't return the errors now you soon will be locked with errors that you can't return to the client because the API doesn't allow it, so in the current state a can't use the lib.

A would like to propose you to move to a new system with [the error_chain package](https://docs.rs/error-chain/0.7.1/error_chain/) and improve the error handling.

It's an heavy operation and I lead to a lot's of breaking changes so I forked the project and I will make you a PR soon in case you are interested.

**Comment by hugues31** [comment]
Hi!
Thanks for your input ! I'm currently trying to improve the `Pair` enum so I don't have the time to look at a better error handling solution for now but yours seems fine. I keep an eye on your fork :)

**Comment by hugues31** [comment]
Error handling improvement with 749b26ab76ada9012e954fa132900490422c8c65

**Comment by hugues31** [comment]
For some reason, you don't seem to appear on the contributors page ([here](https://github.com/hugues31/coinnect/graphs/contributors)). I'll be happy to fix this if you know how to it (I suppose you had a bad git config when you made the commits)
