### ISSUE TITLE
Create a generic credential system

### ISSUE THREAD

**Issue by Peltoche** [hugues31/coinnect#20]
# Issue
Each client can have its proper need for initialization and connection. The current way is to put everything in arguments but it will quickly become very heavy.

Example:
```rust
BitstampApi::new(/*Hashmap<&str, &str>*/);
Kraken::new(&str, &str);
FuturAPI::new(....)
```

The other issue is for `Coinnect` which must handle all the differences. For now it need to take all the arguments, even the useless:
```rust
Coinnect::new(Exchange::Poloniex, "key", "secret", None /*useless*/);
```
This method is not sustainable, what is the next market need another specific argument? And the next one? etc...

# Proposed solution

Create a generic `Credential` which handle all the specific parsing for each market config and an interface returing a `Hashmap<&str, &str>`:

```rust
let polo_creds = Poloniex::Credentials::new("key", "secret")
Coinnect::new(Exchange::Poloniex, polo_creds)
// or
let polo_creds_2 = Poloniex::Credentials::from_file("./creds");
Exchanges::Poloniex::new(polo_creds);
```

The markets `new` method could look like:
```rust
fn new(creds: T): where T: Credential {
  let data: Hashmap<&str, &str> = creds.retrieve();
  let secret = data["secret"]
 // ...
}
```

**Comment by hugues31** [comment]
Seems fine to me 👍

**Comment by ainestal** [comment]
Agree with the problem and the solution

**Comment by Peltoche** [comment]
Ok, so I start the code.
