### ISSUE TITLE
Fix credentials format

### ISSUE THREAD

**Issue by Peltoche** [hugues31/coinnect#21]
# Issue
In the current state the config file look like: 
```json
     {
         "account_bitstamp": {
             "exchange"   : "bitstamp",
             "api_key"    : "1234567890ABCDEF1234567890ABCDEF",
             "api_secret" : "1234567890ABCDEF1234567890ABCDEF",
             "customer_id": "123456"
         }
     }
```

- The key object `account_bitstamp` not very practical and the `exchange` field is useless.
- We need to ask the key used for each config object: 
```rust
pub fn new_from_file(config_name: &str, path: PathBuf) -> /...
```
- We can't load automatically a bunch of config in one time (as we don't know the keys used)

# Solution
We force the key format to market name and we remove the useless `exchange` field:
```json
     {
         "bitstamp": { // mandatory format
             "api_key"    : "1234567890ABCDEF1234567890ABCDEF",
             "api_secret" : "1234567890ABCDEF1234567890ABCDEF",
             "customer_id": "123456"
         }
     }
```

- We simplify the `new_from_file` proto and made it generic:
```rust
pub fn new_from_file(path: PathBuf) -> /...

//allow some cool future features like

let clients = Coinnect::new_clients_from_file("./config")
for client in clients {
  client.ticker().unwrap()
}
```

**Comment by hugues31** [comment]
This was designed in a way that a user may have multiples accounts on the same exchange. What if this is the case with your solution? The user should keep his accounts in separate files?

**Comment by Peltoche** [comment]
Ha... well played!

I was not aware of the multi-account system and this is a great idea. Knowing this, it's all good.

Closed
