### ISSUE TITLE
Establish some workflows

### ISSUE THREAD

**Issue by Peltoche** [hugues31/coinnect#24]
# Issue

For now:
- Everybody push or merge directly on master
- There is no lib versionning
- The documentation is manually updated

# Proposed Solution
Put some rules. 

Here my propositions:
- Everybody make PR
- Every PR target a "dev" branch
- When the "dev" branch is ready -> merge on master with a tag and release a cargo version with the same tag + automatically create the new doc (I can find/create the script if needed)
- Make every merge in --non-fast-forward ( available in @hugues31 options) for more readability.

**Comment by hugues31** [comment]
I agree with that. I'm a beginner with git (and github, this is my first repo), so I'm not sure if I will do it correctly, especially the --non-fast-forward options.
When you say "automatically create the new doc" do you mean uploading the lib to crates.io to lets doc.rs create and publish the doc ?

**Comment by Peltoche** [comment]
Yes, all that. For the doc I suggest to push it on the repo github-page

**Comment by ainestal** [comment]
I agree with
- PRs for everybody, I miss commits done to master directly and I have to review them manually
- --non-fast-forward
- versioning of the library

About having branches, I don't agree so much. I've been working without branches for some years now and:
- the workflow is much more clear for everybody: developers and users
- there is no divergence between dev (or pre, or staging or any other name) and master

If someone wants to use an old version of the library they can specify the version. For me branches end up creating more problems than they solve. The only caveat is that master has to be always stable and passing all the tests (which should always be the case for any branch anyway)

**Comment by hugues31** [comment]
@ainestal I'm ok with what you say for the branches (even if I don't have your experience).

For the `--non-fast-forward`option, what should I change ? The git config file ? Should I add this to the file:
```
[branch "master"]
    mergeoptions = --no-ff
```

**Comment by Peltoche** [comment]
My bad, the option is only on Gitlab but you can have the same result by changing theses options in the project parameters:
- remove the 'Allow rebase merging' 
- remove 'Allow squash merging'.

Ok for the one branch, but how do we trigger the lib/doc versioning? With tags?

**Comment by hugues31** [comment]
@Peltoche I have updated the project settings according to what you said.

**Comment by ainestal** [comment]
@Peltoche we can do it with tags, yes. Releases are created automatically in github and it's a good way to keep track of the versions.
The biggest problem with this approach is that the tags have to be created manually after the merge, but merging is even more manual anyway when the branches diverge after some time of development.
So, @hugues31 , are you ok creating the tags when the merges are done?

**Comment by hugues31** [comment]
So we increment the version for every PR being merged ?

**Comment by Peltoche** [comment]
For me yep.

I think the best way to handle correctly the versioning is to follow the [semantic versioning conventions](http://semver.org/).

If we decide to follow them, the major rules are:
- Bump the major for any breaking change (V1.3.1 -> V2.0.0)
- Bump the minor for any API change without breaks (V1.3.4 -> V1.4.0)
- Bump the patch for any change without API change (V1.3.4 -> V1.3.5)
- The V1.0.0 and above means stable and production ready (no more breaking changes, or very few)
- Before stable we only bump the minor (and patch?) versions (V0.12.3 -> V0.13.0)

**Comment by ainestal** [comment]
Agree.

Just a small request: please, when naming the versions don't include the "v" character.

**Comment by ainestal** [comment]
@hugues31 could you bump the version to 0.3.1 ? The current version is messed up, version 0.3.0 doesn't include the credentials yet. Version 0.3 doesn't exist on crates.io

The tag in github should match the version of the library in Cargo.toml .

Btw, I was researching how to automatically create the tag and push it to Github from Travis. Apparently in order to make it work Travis needs the repository owner key (encrypted) in the code, which is a dangerous practice. You can read about it in: [Feature Request: automatically create (and push) Git tag after successful build](https://github.com/travis-ci/travis-ci/issues/1476)

**Comment by Peltoche** [comment]
I strongly recommend to handle the versions manually

If I make a PR with some really bad code (even malicious one) in it but the build go green we don't want to trigger a new version and a push it to crate.io. Push to many times in "production" could be dangerous if we don't make very serious PR because once the code is on crate.io we can't delete it and some user could use it in production.

Less versions but with a better quality could be a good idea.

**Comment by Peltoche** [comment]
[some script to publish documentation](https://github.com/Peltoche/ical-rs/blob/master/publish-doc.sh)

**Comment by ainestal** [comment]
@Peltoche , I agree. After taking a look into automating the process I can't say I like the idea. That example I linked earlier is just to share the knowledge.

**Comment by hugues31** [comment]
Seems fine, I'll bump the version now :)

**Comment by hugues31** [comment]
I believe that I have delayed the tag creation and the merge commits so that each release contains the code of the old release. Is it right?

**Comment by ainestal** [comment]
Do you mean that you bumped the version 1 number with 2 PRs ? If that's the case, that's fine since you merged them so close in time, no user will have the need to go to that PR between versions. If someone needs to go to a specific point in the history of commits, the reference to a specific commit can be used. Tags are for users (and for us) to be able to easily distinguish between states of the repository

**Comment by hugues31** [comment]
No I didn't want to mean that but I'm not sure to understand the tag system well yet and since I have a limited internet access for now I can not check properly what I've done :)

**Comment by hugues31** [comment]
I think it's fine now, I close
