### ISSUE TITLE
Moving Currency and Pair to Types so all the types live under the same module

### ISSUE THREAD

**Issue by ainestal** [hugues31/coinnect#31]
I find it confusing when using the library that these 2 types are not in the types mod. It also forces the user to import other 2 mods instead of just types.

I also understand they are different from the rest of types implemented in the types mod.

So I'd like to ask you about moving them. What are your thoughts?

**Comment by hugues31** [comment]
Yes I agree. Maybe we can make a "super" Types mod (folder) and put inside it Pair+Currency in one sub-mod, and the others types in an other one (no idea for the name yet)

**Comment by ainestal** [comment]
I was thinking about just moving them into coinnect::types . I don't see the benefit for the user in having pair and currency in a specific mod.

**Comment by hugues31** [comment]
Oh you mean in the same file, I see :) You can post a PR if you want or I will make one tomorrow

**Comment by ainestal** [comment]
This is the PR #32

**Comment by hugues31** [comment]
PR merged. I close
