### ISSUE TITLE
BTC fork

### ISSUE THREAD

**Issue by ainestal** [hugues31/coinnect#35]
I'm opening this issue as a discussion thread.

Looks like the Bitcoin fork will happen in the next future, not far from now. There will be different names for the Bitcoin Unlimited and Bitcoin Core across different exchanges. Luckily for us look like the 3 exchanges we are currently supporting will maintain the BTC (or XBT) for Bitcoin Core (the current bitcoin) and will use a different name for Bitcoin Unlimited. For me, with the information I currently have, that means we could just continue using the current convention and create new pairs and currency with the new name for the Bitcoin Unlimited.

What do you think about this?

**Comment by hugues31** [comment]
Yes I follow the event closely and I think a simple update of pairs should suffice. Time will tell us!

**Comment by hugues31** [comment]
I will add the new pairs very soon (BCH for Kraken)

**Comment by hugues31** [comment]
New pairs have been added with #40, I close.
