### ISSUE TITLE
OpenAPI & codegen

### ISSUE THREAD

**Issue by crackcomm** [hugues31/coinnect#47]
@hugues31 What do you think about creating [OpenAPI](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md) specifications for exchanges and generating client code?

**Comment by hugues31** [comment]
Didn't know OpenAPI since now, sounds very interesting but is a huge rework of the lib :/ so if anyone is interested in following this path, I encourage them, but I personally don't have the time to invest in this potential improvement

**Comment by crackcomm** [comment]
There seems to already exist a [swagger-codegen](https://github.com/swagger-api/swagger-codegen) template for [rust](https://github.com/swagger-api/swagger-codegen/tree/master/modules/swagger-codegen/src/main/resources/rust).

**Comment by tbourvon** [comment]
This looks to me like it should be the top priority issue. Coinnect deals with (crypto)currencies, and as such reliability, stability and easiness of maintenance are very important. I'm probably going to start investigating this and maybe work on this first (before working on adding exchanges or futures).

**Comment by tbourvon** [comment]
As you can probably see, I've pushed a PR with a first sketch of a GDAX OpenAPI specification, along with the instructions to generate the Rust API from it. Please don't hesitate to comment on how you feel about this.

**Comment by crackcomm** [comment]
I certainly love that :) thank you

**Comment by crackcomm** [comment]
I would suggest keeping those auto-generated clients in a crate, on this type safe clients we can then implement more general traits, general for all exchanges.

I think we would need to split the traits as much as possible, eq. `Ticker` trait etc.

**Comment by crackcomm** [comment]
I can recommend using [editor.swagger.io](http://editor.swagger.io/) for editing the spec, it catches all errors.
