### ISSUE TITLE
Docs on docs.rs do not work anymore

### ISSUE THREAD

**Issue by hugues31** [hugues31/coinnect#49]
Build log says :
```
error[E0460]: found possibly newer version of crate `idna` which `hyper` depends on
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/coinnect-0.5.3/src/lib.rs:33:1
   |
33 | extern crate hyper;
   | ^^^^^^^^^^^^^^^^^^^
   |
   = note: perhaps that crate needs to be recompiled?
   = note: crate `idna` path #1: /home/cratesfyi/cratesfyi/debug/deps/libidna-e17fe1ecab30d084.rlib
   = note: crate `idna` path #2: /home/cratesfyi/cratesfyi/debug/deps/libidna-61e19868261f71ed.rlib
   = note: crate `hyper` path #1: /home/cratesfyi/cratesfyi/debug/deps/libhyper-103a835b55757827.rlib

error: aborting due to previous error
```
And I have no idea on how to solve that

**Comment by crackcomm** [comment]
Try removing the `build`, `debug` dirs

**Comment by hugues31** [comment]
yes but it happens on the docs.rs website, not on my local machine, so i don't have access to this folder

**Comment by crackcomm** [comment]
I believe this is docs.rs [issue](https://github.com/onur/docs.rs/issues/23) then.

**Comment by hugues31** [comment]
#50 does not seem to refresh the docs.rs cache :/ I don't know what to do to fix it

**Comment by crackcomm** [comment]
I was trying to install [cargo-tree](https://github.com/sfackler/cargo-tree) or [cargo-graph](https://github.com/kbknapp/cargo-graph) to identify the package that requires conflicting version of idna but build fails on my windows.

**Comment by crackcomm** [comment]
Maybe you should try updating to latest hyper?

**Comment by hugues31** [comment]
It's a breaking change since 0.11 version brings the async feature so this is not trivial. I was considering replacing Hyper by Reqwest. By doing this, we can try to make an async version around Futures more easily. What do you think?

**Comment by crackcomm** [comment]
I was not aware reqwest released with async API. This is probably a good idea then, if it simpler to use.

**Comment by hugues31** [comment]
Solved, I close!
