### ISSUE TITLE
Order type for Poloniex

### ISSUE THREAD

**Issue by doomsplayer** [hugues31/coinnect#64]
Poloniex supports several additional order types like `FillOrKill`. I have an implementation [here](https://github.com/doomsplayer/coinnect/commit/4da736fc2f09aa59e21e465a58f62774e911f11e), which introduces additional parameters to `buy`, `sell`, and `move_order`. Not sure if it works for you.

**Comment by hugues31** [comment]
Whoa such a shame I didn't respond to you sooner, sorry. I must have skipped the notification..
Your implementation seems fine to me, if you are kind enough to make a PR, I'll be happy to merge it :) If you have not the time and if you agree, I will do it myself in the next few days
