### ISSUE TITLE
Least common functions

### ISSUE THREAD

**Issue by ainestal** [hugues31/coinnect#8]
Since different exchanges offer different types of data, what is the least common functions we want to implement in all the exchanges integrated?

In other words, how do the trait ExchangeApi has to be?

**Comment by hugues31** [comment]
Maybe we can look at the [XChange](https://github.com/timmolter/XChange) library to see what we can implement.

**Comment by ainestal** [comment]
Yes, that is a good starting point. 

Btw, that library is growing fast ! It's pretty impressive the amount of collaborators they have

**Comment by hugues31** [comment]
I close since this can be discussed as a per function basis (add_order, balances, ...)
